spring:
  application:
    name: API Gateway Service
  api:
    title: API Gateway Micro Service
    version: 1.0.0
    description: API Gateway Micro Service description
    base-package: edu.miu.cs590.SA.Ecommerce
    contact-name: Terbinos
    contact-email: tchekol@miu.edu
server:
  port: ${SERVER_PORT}

jwt:
  expiry: ${EXPIRY}
  secret: ${SECRET}

credential.username: ${USERNAME}
credential.password: ${PASSWORD}

account:
  service:
    url: ${ACCOUNT_SERVICE_URL}
    api:
      login: ${ACCOUNT_LOGIN_ENDPOINT}
      account: ${ACCOUNT_ENDPOINT}
      register: ${ACCOUNT_REGISTER_ENDPOINT}

product:
  service:
    url: ${PRODUCT_SERVICE_URL}
    api:
      product: ${PRODUCT_ENDPOINT}

order:
  service:
    url: ${ORDER_SERVICE_URL}
    api:
      order: ${ORDER_ENDPOINT}
