spring:
  application:
    name: API Gateway Service
  api:
    title: API Gateway Micro Service
    version: 1.0.0
    description: API Gateway Micro Service description
    base-package: edu.miu.cs590.SA.Ecommerce
    contact-name: Terbinos
    contact-email: tchekol@miu.edu
server:
  port: ${SERVER_PORT}

jwt:
  expiry: ${EXPIRY}
  secret: ${SECRET}

credential.username: ${USERNAME}
credential.password: ${PASSWORD}

base_url: ${BASE_URL}
account_prefix: ${ACCOUNT_PREFIX}
product_prefix: ${PRODUCT_PREFIX}
order_prefix: ${ORDER_PREFIX}
login_prefix: ${LOGIN_PREFIX}
register_prefix: ${REGISTER_PREFIX}