server:
  port: ${SERVER_PORT}
spring:
  datasource:
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_PRODUCER_SERVER}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

credential.username: ${USERNAME}
credential.password: ${PASSWORD}
jwt:
  expiry: ${JWT_EXPIRE}
  secret: ${JWT_SECRET}

kafka:
  publish:
    below_threshold_topic: ${TOPIC_NAME}
