apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-db-deployment
  labels:
    app: orderdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderdb
  template:
    metadata:
      labels:
        app: orderdb
    spec:
      containers:
        - name: orderdb
          image: mysql:latest
          ports:
          - containerPort: 3306
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: orderdb-secret
                key: mysql-root-password
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: orderdb-config
                key: db_name

---
apiVersion: v1
kind: Service
metadata:
  name: order-db-service
spec:
  selector:
    app: orderdb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
apiVersion: v1
kind: Secret
metadata:
  name: orderdb-secret
type: Opaque
stringData:
  mysql-root-password: cm9vdA==
  mysql-root-username: root
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: orderdb-config
data:
  db_name: order_service