apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-db-deployment
  labels:
    app: paymentdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentdb
  template:
    metadata:
      labels:
        app: paymentdb
    spec:
      containers:
        - name: paymentdb
          image: mysql:latest
          ports:
          - containerPort: 3306
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: paymentdb-secret
                key: mysql-root-password
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: paymentdb-config
                key: db_name 
---
apiVersion: v1
kind: Service
metadata:
  name: payment-db-service
spec:
  selector:
    app: paymentdb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
apiVersion: v1
kind: Secret
metadata:
  name: paymentdb-secret
type: Opaque
stringData:
  mysql-root-password: cm9vdA==
  mysql_root_username: root
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: paymentdb-config
data:
  db_name: payment_service