apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-db-deployment
  labels:
    app: productdb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: productdb
  template:
    metadata:
      labels:
        app: productdb
    spec:
      containers:
        - name: productdb
          image: mysql:latest
          ports:
          - containerPort: 3306
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: productdb-secret
                key: mysql-root-password
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: productdb-config
                key: db_name

---
apiVersion: v1
kind: Service
metadata:
  name: product-db-service
spec:
  selector:
    app: productdb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
apiVersion: v1
kind: Secret
metadata:
  name: productdb-secret
type: Opaque
stringData:
  mysql-root-password: cm9vdA==
  mysql-root-username: root

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: productdb-config
data:
  db_name: product_service