apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-app-deployment
  labels:
    app: account-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account-app
  template:
    metadata:
      labels:
        app: account-app
    spec:
      containers:
        - name: account-app
          image: pyordan/account_service:1.1
          ports:
          - containerPort: 8000
          env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: accountdb-secret
                key: mysql-root-password
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: accountdb-secret
                key: mysql_root_username
          - name: JWT_SECRET
            valueFrom: 
              secretKeyRef:
                name: account-app-secret
                key: jwt-secret
          - name: JWT_EXPIRY
            valueFrom: 
              configMapKeyRef:
                name: account-app-config
                key: jwt_expire
          - name: DB_URL
            valueFrom: 
              configMapKeyRef:
                name: account-app-config
                key: db_url
          - name: SERVER_PORT
            value: "8000"
          - name: DB_NAME 
            valueFrom: 
              configMapKeyRef:
                name: accountdb-config
                key: db_name         
          - name: DB_PORT
            value: "3306"
          

---
apiVersion: v1
kind: Service
metadata:
  name: account-app-service
spec:
  selector:
    app: account-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
apiVersion: v1
kind: Secret
metadata:
  name: account-app-secret
type: Opaque
stringData:
  jwt-secret: FKckg7aj1rt9scui5ik5tr93d0FKckg7aj1rt9scui5ik5tr93d0FKckg7aj1rt9scui5ik5tr93d0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: account-app-config
data:
  db_url: account-db-service
  jwt_expire: "36000000"