apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-app-deployment
  labels:
    app: api-gateway-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway-app
  template:
    metadata:
      labels:
        app: api-gateway-app
    spec:
      containers:
        - name: api-gateway-app
          image: pyordan/api_gateway:1.1
          ports:
          - containerPort: 9000
          env:
          - name: SERVER_PORT
            value: "9000"
          - name: JWT_SECRET
            valueFrom: 
              secretKeyRef:
                name: account-app-secret
                key: jwt-secret
          - name: JWT_EXPIRE
            valueFrom: 
              configMapKeyRef:
                name: account-app-config
                key: jwt_expire
          - name: USERNAME
            valueFrom: 
              secretKeyRef:
                name: api-gateway-app-secret
                key: username
          - name: PASSWORD
            valueFrom: 
              secretKeyRef:
                name: api-gateway-app-secret
                key: password
          - name: ACCOUNT_SERVICE_URL
            value: account-app-service
          - name: ACCOUNT_LOGIN_ENDPOINT
            value: "/login"           
          - name: ACCOUNT_ENDPOINT
            value: "/accounts"           
          - name: ACCOUNT_REGISTER_ENDPOINT
            value: "/register"     
          - name: PRODUCT_SERVICE_URL
            value: product-app-service
          - name: PRODUCT_ENDPOINT
            value: "/api/products"   
          - name: ORDER_SERVICE_URL
            value: order-app-service 
          - name: ORDER_ENDPOINT
            value: "/api/orders"    

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-app-service
spec:
  selector:
    app: api-gateway-app
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-app-secret
type: Opaque
stringData:
  username: cm9vdA==
  password: cm9vdA==