apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: api-gateway-app
          servicePort: 9000

