apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-app-deployment
  labels:
    app: payment-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-app
  template:
    metadata:
      labels:
        app: payment-app
    spec:
      containers:
        - name: payment-app
          image: pyordan/payment_service:1.0
          ports:
          - containerPort: 8002
          env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: paymentdb-secret
                key: mysql-root-password
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: paymentdb-secret
                key: mysql_root_username
          - name: DB_URL
            valueFrom: 
              configMapKeyRef:
                name: payment-app-config
                key: db_url
          - name: SERVER_PORT
            value: "8002"
          - name: CC_PAYMENT_URL
            value: cc-payment-app-service
          - name: CC_ENDPOINT
            value: "api/cc"
          - name: PAYPAL_PAYMENT_URL
            value: paypal-payment-app-service
          - name: PAYPAL_ENDPOINT
            value: "api/paypal"
          - name: DB_NAME 
            valueFrom: 
              configMapKeyRef:
                name: paymentdb-config
                key: db_name                 

---
apiVersion: v1
kind: Service
metadata:
  name: payment-app-service
spec:
  selector:
    app: payment-app
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-app-config
data:
  db_url: payment-db-service
  topic-name: topic
  mysql-root-username: root