apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-app-deployment
  labels:
    app: product-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-app
  template:
    metadata:
      labels:
        app: product-app
    spec:
      containers:
        - name: product-app
          image: pyordan/product_service:1.0
          ports:
          - containerPort: 8001
          env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: productdb-secret
                key: mysql-root-password
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: productdb-secret
                key: mysql-root-username
          - name: JWT_SECRET
            valueFrom: 
              secretKeyRef:
                name: account-app-secret
                key: jwt-secret
          - name: JWT_EXPIRY
            valueFrom: 
              configMapRef:
                name: account-app-config
                key: jwt-expire
          - name: DB_URL
            valueFrom: 
              configMapRef:
                name: product-app-config
                key: db_url
          - name: SERVER_PORT
            value: 8001
          - name: DB_NAME 
            valueFrom: 
              configMapRef:
                name: productdb-config
                key: db_name         
          - name: TOPIC_NAME
            valueFrom:            
              configMapRef:
                name: product-app-config
                key: topic-name          

---
apiVersion: v1
kind: Service
metadata:
  name: product-app-service
spec:
  selector:
    app: product-app
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: product-app-config
data:
  db_url: product-db-service
  topic-name: topic