apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-app-deployment
  labels:
    app: product-app
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: product-app
  template:
    metadata:
      labels:
        app: product-app
    spec:
      containers:
        - name: product-app
          image: pyordan/product_service:1.1
          ports:
          - containerPort: 8001
          env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: productdb-secret
                key: mysql-root-password
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: productdb-secret
                key: mysql-root-username
          - name: JWT_SECRET
            valueFrom: 
              secretKeyRef:
                name: account-app-secret
                key: jwt-secret
          - name: JWT_EXPIRE
            valueFrom: 
              configMapKeyRef:
                name: account-app-config
                key: jwt_expire
          - name: DB_URL
            valueFrom: 
              configMapKeyRef:
                name: product-app-config
                key: db_url
          - name: SERVER_PORT
            value: "8001"
          - name: DB_NAME 
            valueFrom: 
              configMapKeyRef:
                name: productdb-config
                key: db_name         
          - name: TOPIC_NAME
            valueFrom:            
              configMapKeyRef:
                name: product-app-config
                key: topic-name
          - name: DB_PORT
            value: "3306"          
          - name: USERNAME
            valueFrom: 
              secretKeyRef:
                name: product-app-secret
                key: username
          - name: PASSWORD
            valueFrom: 
              secretKeyRef:
                name: product-app-secret
                key: password
          - name: KAFKA_PRODUCER_SERVER
            value: kafka-service                
---
apiVersion: v1
kind: Service
metadata:
  name: product-app-service
spec:
  selector:
    app: product-app
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: product-app-config
data:
  db_url: product-db-service
  topic-name: topic

---
apiVersion: v1
kind: Secret
metadata:
  name: product-app-secret
type: Opaque
stringData:
  username: cm9vdA==
  password: cm9vdA==
